# AuroraQ Production 설정 파일

# 거래 설정
trading:
  max_position_size: 0.1          # 최대 포지션 크기 (10%)
  emergency_stop_loss: 0.05       # 긴급 손절선 (5%)
  max_daily_trades: 10            # 일일 최대 거래 횟수
  update_interval_seconds: 60     # 업데이트 간격 (초)
  lookback_periods: 100           # 데이터 룩백 기간
  min_data_points: 50             # 최소 데이터 포인트

# 전략 설정
strategy:
  rule_strategies:                # 사용할 Rule 전략 목록
    - "RuleStrategyA"
    - "RuleStrategyB"
    - "RuleStrategyC"
  enable_ppo: true                # PPO 전략 활성화
  hybrid_mode: "ensemble"         # 하이브리드 모드 (ensemble/consensus/competition)
  execution_strategy: "market"    # 실행 전략 (market/limit/smart)
  risk_tolerance: "moderate"      # 리스크 허용도 (conservative/moderate/aggressive)
  ppo_weight: 0.3                # PPO 가중치
  min_confidence: 0.6             # 최소 신뢰도

# 리스크 관리
risk:
  max_drawdown: 0.15              # 최대 낙폭 허용치 (15%)
  max_portfolio_risk: 0.02        # 최대 포트폴리오 리스크 (2%)
  position_concentration_limit: 0.3  # 포지션 집중도 한계 (30%)
  correlation_threshold: 0.7      # 상관관계 임계값
  var_confidence_level: 0.95      # VaR 신뢰수준

# 알림 설정
notifications:
  enable_notifications: true      # 알림 활성화
  channels:                       # 알림 채널
    - "console"
    - "file"
  email_recipients: []            # 이메일 수신자 목록
  slack_webhook: null             # 슬랙 웹훅 URL
  telegram_bot_token: null        # 텔레그램 봇 토큰
  telegram_chat_id: null          # 텔레그램 채팅 ID

# 시스템 설정
log_level: "INFO"                 # 로그 레벨 (DEBUG/INFO/WARNING/ERROR)
data_path: "data"                 # 데이터 저장 경로
model_path: "models"              # 모델 저장 경로
results_path: "results"           # 결과 저장 경로

# 센티멘트 분석 설정 (선택사항)
sentiment:
  enable_sentiment: false         # 센티멘트 분석 활성화
  news_sources:                   # 뉴스 소스
    - "coindesk"
    - "yahoo_finance"
  update_interval_minutes: 30     # 센티멘트 업데이트 간격 (분)
  sentiment_weight: 0.2           # 센티멘트 가중치

# 백테스트 설정 (테스트/데모 모드용)
backtest:
  start_date: "2024-01-01"        # 백테스트 시작일
  end_date: "2024-12-31"          # 백테스트 종료일
  initial_capital: 100000         # 초기 자본 ($)
  commission: 0.001               # 수수료 (0.1%)

# 최적화 설정
optimization:
  enable_auto_optimization: false  # 자동 최적화 활성화
  optimization_interval_days: 7    # 최적화 간격 (일)
  parameter_ranges:                 # 파라미터 범위
    ppo_weight: [0.2, 0.3, 0.4, 0.5]
    min_confidence: [0.5, 0.6, 0.7]