# AuroraQ Prometheus 설정 (간단 버전)
global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # AuroraQ 메트릭 API 서버
  - job_name: 'auroraq-metrics'
    static_configs:
      - targets: ['host.docker.internal:8001']
    metrics_path: '/metrics'

  # 실시간 트레이딩 엔진
  - job_name: 'trading-engine'
    static_configs:
      - targets: ['host.docker.internal:8002']
    metrics_path: '/metrics'

  # Redis 모니터링
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    
  # PostgreSQL 모니터링
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']