version: '3.8'

services:
  sentiment-service:
    build: .
    container_name: auroraQ-sentiment-service
    ports:
      - "8000:8000"    # FastAPI REST API
      - "50051:50051"  # gRPC service
    environment:
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=INFO
      - FINBERT_MODEL_PATH=/app/models/finbert
      - MAX_WORKERS=4
      - CACHE_TTL=300
      - PROMETHEUS_PORT=8080
    volumes:
      - sentiment_models:/app/models
      - sentiment_cache:/app/cache
      - sentiment_logs:/app/logs
    depends_on:
      - redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: auroraQ-sentiment-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  prometheus:
    image: prom/prometheus:latest
    container_name: auroraQ-sentiment-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped

volumes:
  sentiment_models:
    driver: local
  sentiment_cache:
    driver: local
  sentiment_logs:
    driver: local
  redis_data:
    driver: local
  prometheus_data:
    driver: local

networks:
  default:
    name: auroraQ-sentiment-network
    driver: bridge