# Power Search Queries for Feedly
queries:
  - "Powell AND Fed"
  - "Bitcoin AND ETF"
  - "Ethereum AND upgrade"
  - "interest rate AND hike"
  - "inflation AND USA"
  - "FOMC AND decision"
  - "Federal Reserve AND policy"
  - "SEC AND crypto"
  - "Binance AND investigation"
  - "BlackRock AND Bitcoin"
  - "Elon Musk AND market"
  - "AI AND investment"
  - "recession AND forecast"
  - "Nasdaq AND drop"
  - "S&P500 AND rally"
  - "GDP AND decline"
  - "Dow Jones AND volatility"
  - "yield curve AND inverted"
  - "ECB AND interest rate"
  - "BoJ AND policy change"
  - "gold AND inflation hedge"
  - "oil prices AND OPEC"
  - "China AND economic data"
  - "Evergrande AND debt"
  - "tech stocks AND correction"
  - "Apple AND earnings"
  - "Tesla AND delivery"
  - "Amazon AND layoff"
  - "Meta AND metaverse"
  - "chip shortage AND supply chain"
  - "unemployment AND rise"
  - "jobless claims AND US"
  - "housing market AND crash"
  - "consumer sentiment AND US"
  - "crypto regulation AND US"
  - "stablecoin AND risk"
  - "Bitcoin AND whale activity"
  - "altcoins AND surge"
  - "DeFi AND hack"
  - "NFT AND sales"
  - "FedNow AND launch"
  - "BRICS AND currency"
  - "US dollar AND strength"
  - "treasury yield AND 10 year"
  - "volatility index AND VIX"
  - "options expiry AND market"
  - "SPY AND flow"
  - "BTC AND liquidation"
  - "crypto AND fear index"
  - "global recession AND 2025"
  - "soft landing AND risk"
