cumulative_gain_bonus: 0.5
cumulative_loss_penalty: 1.0
early_exit_penalty: 0.5
fee_rate:
  limit: 0.0002
  market: 0.0004
min_hold_period: 3
reward:
  max_holding: 30
  min_holding: 3
  time_penalty: -0.01
reward_weights:
  drawdown: -0.7
  profit: 1.0
  sharpe_ratio: 0.3
  volatility: -0.5
risk_adjustment:
  hold_reward: 0.1
  leverage_penalty: -0.3
  stop_loss_penalty: -0.5
scaling:
  reward_clip_max: 10.0
  reward_clip_min: -10.0
sentiment_match_bonus: 0.2
sentiment_mismatch_penalty: 0.2
sharpe_bonus_weight: 0.5
slippage: 0.0005
