# Prometheus configuration for sentiment service monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Sentiment Service metrics
  - job_name: 'sentiment-service'
    static_configs:
      - targets: ['sentiment-service:8080']
    scrape_interval: 10s
    metrics_path: /metrics
    
  # Redis metrics (if redis-exporter is used)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Alerting rules (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           # - alertmanager:9093